// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------- //
// pio_seq //
// ------- //

#define pio_seq_wrap_target 0
#define pio_seq_wrap 1

static const uint16_t pio_seq_program_instructions[] = {
            //     .wrap_target
    0x6001, //  0: out    pins, 1                    
    0x0000, //  1: jmp    0                          
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program pio_seq_program = {
    .instructions = pio_seq_program_instructions,
    .length = 2,
    .origin = -1,
};

static inline pio_sm_config pio_seq_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pio_seq_wrap_target, offset + pio_seq_wrap);
    return c;
}

static inline void pio_seq_init(PIO pio, uint sm, uint offset, uint pin) {
    pio_sm_config c = pio_seq_program_get_default_config(offset);
    // Map the state machine's OUT pin group to one pin, namely the `pin`
    // parameter to this function.
    sm_config_set_out_pins(&c, pin, 1);
    // Set this pin's GPIO function (connect PIO to the pad)
    pio_gpio_init(pio, pin);
    float div = (float)65536;
    sm_config_set_clkdiv(&c, div);
    // Set the pin direction to output at the PIO
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, true);
    // Load our configuration, and jump to the start of the program
    pio_sm_init(pio, sm, offset, &c);
    // Set the state machine running
    pio_sm_set_enabled(pio, sm, true);
}

#endif
